#
# Copyright 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ARM64 device
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

BOARD_VENDOR_SEPOLICY_DIRS += device/stm/stm32mp2/sepolicy/vendor

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += device/stm/stm32mp2/sepolicy/system_ext/private
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += device/stm/stm32mp2/sepolicy/system_ext/public
PRODUCT_PRIVATE_SEPOLICY_DIRS += device/stm/stm32mp2/sepolicy/product/private
# PRODUCT_PUBLIC_SEPOLICY_DIRS += device/stm/stm32mp2/sepolicy/product/public

# =========================================================== #
# PREBUILT configuration                                      #
# =========================================================== #

# Path for Linux kernel files
TARGET_PREBUILT_DTB_PATH := device/stm/stm32mp2-kernel/prebuilt/dts
TARGET_PREBUILT_DTBO_PATH := device/stm/stm32mp2-kernel/prebuilt/dts

BOARD_PREBUILT_DTBIMAGE_DIR := device/stm/stm32mp2-kernel/prebuilt/dts/$(SOC_VERSION)

# Pass unsigned dtbo image (generated by build/tasks/dt.mk) to Android
# build system for AVB signing
DTBO_UNSIGNED := dtbo-unsigned.img
# $(PRODUCT_OUT) hasn't been defined yet, so use "=" instead of ":="
# so that it is resolved later
BOARD_PREBUILT_DTBOIMAGE = $(PRODUCT_OUT)/$(DTBO_UNSIGNED)

# Path for primary (TF-A) and secondary (U-Boot) bootloader files
TARGET_PREBUILT_PBL := device/stm/stm32mp2-bootloader/prebuilt/fsbl/$(SOC_VERSION)-$(BOARD_FLAVOUR)
TARGET_PREBUILT_SBL := device/stm/stm32mp2-bootloader/prebuilt/ssbl/$(SOC_VERSION)-$(BOARD_FLAVOUR)
TARGET_PREBUILT_DDR := device/stm/stm32mp2-bootloader/prebuilt/ddr/$(SOC_FAMILY)
TARGET_PREBUILT_TOOLS := device/stm/stm32mp2-bootloader/prebuilt/tools

# Path for splash screen image (U-Boot)
TARGET_SPLASH_BMP := device/stm/stm32mp2/splash/stmicroelectronics.bmp

# Path for OP-TEE OS files
TARGET_PREBUILT_TEE := device/stm/stm32mp2-tee/prebuilt/$(SOC_VERSION)-$(BOARD_FLAVOUR)/optee_os

# Path to misc.img (boot control) which can be re-generated using miscgen
TARGET_PREBUILT_MISC := device/stm/stm32mp2/misc.img

# Path to teefs.img (OP-TEE encrypted file system, fixed to 128MB)
TARGET_PREBUILT_TEEFS := device/stm/stm32mp2/teefs.img

# ================= #
# TEE configuration #
# ================= #
ifeq ($(BOARD_SECURITY),optee)

BUILD_OPTEE_MK=device/stm/stm32mp2-tee/optee.mk

ifeq ($(BOARD_DISK_TYPE),sd)
# Use dedicated partition (ree fs)
CFG_TEE_FS_PARENT_PATH=/mnt/vendor/teefs/optee
BOARD_ROOT_EXTRA_SYMLINKS += /mnt/vendor/teefs:/teefs
else
# Use RPMB (need to deactivate emulator in tee supplicant
RPMB_EMU = 0
endif

endif
